server:
  port: 8082

otel:
#  traces:
#    exporter: console
  exporter:
    otlp:
      protocol: grpc
      endpoint: http://localhost:4317
  resource:
    attributes:
      service.name: order-service
      service: order-service
      env: dev

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/opentelemetry
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS:localhost:19092,localhost:29092,localhost:39092}
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: true