server:
  port: 8081

otel:
  exporter:
    otlp:
      protocol: grpc
      endpoint: http://localhost:4317
  resource:
    attributes:
      service.name: invoice-service
      service: invoice-service
      env: dev

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/opentelemetry
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer